---
spring:
  profiles: memdb
  datasource:
    username: sa
    password: sa
    url: jdbc:hsqldb:mem:hsql_db
---
spring:
  profiles: simple
  datasource:
    schema: classpath:hsql/schema/simple-sample.sql
    data: classpath:hsql/data/simple-sample.sql

easy-dev:
  swagger:
    base-package: cn.tac.framework.easydev.sample
    title: sample project api docs
    version: 0.0.1
